### ISSUE TITLE
[BUG] 504 Gateway Time-out

### ISSUE THREAD

**Issue by SangwonYoon** [boostcampaitech5/level3_nlp_finalproject-nlp-08#51]
## Background
- API 요청이 밀리는 경우, LLM의 답변 생성을 기다리다가 time out이 발생함. time out 제한 시간을 늘려줘야 할 것으로 보임
- 에러 재현 방법: 창 2개 켜놓고 각각의 창에서 요청을 보내면 2번째로 요청 보낸 창에서 에러를 확인할 수 있음 (개발자 도구 활용)

## Todo 
- [ ] 미정

**Comment by Kim-Ju-won** [comment]
@SangwonYoon 관련 내용은 nginx proxy server 설정 사항으로 코드 변동 없이 에러가 해결 가능합니다. 
아래와 같이 nginx 설정을 바꾸어 두었습니다. 참고하도록 내용올려두고 PR 없이 issue close합니다. 
```
server {
        listen 80;
        listen [::]:80;

        server_name server name ;

        root /build_page_location;
        index index.html;

        location /generate {

                proxy_pass backend_server;
                proxy_connect_timeout 500;
                proxy_send_timeout 500;
                proxy_read_timeout 500;
        }
}
```
